#include <torch/extension.h>

#include <vector>

std::vector<at::Tensor> adaptive_rowcol_quant_fast_cuda(
    const at::Tensor& input,
    double base_ratio,
    double min_ratio,
    double max_ratio,
    double reference_heaviness,
    int64_t capacity,
    bool emit_dense_main,
    int64_t stats_threads,
    int64_t fill_threads,
    int64_t columnwise_source,
    int64_t rht_random_sign_mask_t,
    bool overlap_columnwise,
    bool direct_nomask,
    bool build_active_schedule,
    bool build_unsorted_active_rows,
    double threshold_sigma_override);

int64_t adaptive_rowcol_scan_temp_bytes_cuda(int64_t rows);

int64_t adaptive_rowcol_active_sort_temp_bytes_cuda(int64_t rows);

std::vector<at::Tensor> adaptive_rowcol_quant_fast_out_cuda(
    const at::Tensor& input,
    const at::Tensor& flat_indices,
    const at::Tensor& outlier_values,
    const at::Tensor& outlier_cols,
    const at::Tensor& row_counts,
    const at::Tensor& row_offsets,
    const at::Tensor& selection_masks,
    const at::Tensor& num_selected,
    const at::Tensor& overflow,
    const at::Tensor& stats_amax,
    const at::Tensor& rowwise_data,
    const at::Tensor& rowwise_scale,
    const at::Tensor& columnwise_data,
    const at::Tensor& columnwise_scale,
    const at::Tensor& columnwise_amax,
    const at::Tensor& rht_output_t,
    const at::Tensor& scan_temp,
    const at::Tensor& packed_records,
    const at::Tensor& active_rows_heavy_light,
    const at::Tensor& active_row_count,
    const at::Tensor& active_sort_rows_in,
    const at::Tensor& active_sort_rows_out,
    const at::Tensor& active_sort_keys_in,
    const at::Tensor& active_sort_keys_out,
    const at::Tensor& active_sort_temp,
    const at::Tensor& hardcap_score_max,
    const at::Tensor& hardcap_histogram,
    double base_ratio,
    double min_ratio,
    double max_ratio,
    double reference_heaviness,
    int64_t capacity,
    int64_t stats_threads,
    int64_t fill_threads,
    int64_t columnwise_source,
    int64_t rht_random_sign_mask_t,
    bool overlap_columnwise,
    bool auto_expand_capacity,
    bool emit_packed_records,
    bool build_active_schedule,
    bool emit_direct_split,
    int64_t direct_policy_mode,
    int64_t direct_param0,
    int64_t direct_param1,
    bool direct_use_bucket,
    bool direct_no_host_slice);

std::vector<at::Tensor> adaptive_rowcol_quant_fast_padded_out_cuda(
    const at::Tensor& input,
    const at::Tensor& padded_values,
    const at::Tensor& padded_cols,
    const at::Tensor& row_counts,
    const at::Tensor& selection_masks,
    const at::Tensor& num_selected,
    const at::Tensor& overflow,
    const at::Tensor& overflow_rows,
    const at::Tensor& overflow_cols,
    const at::Tensor& overflow_values,
    const at::Tensor& overflow_count,
    const at::Tensor& stats_amax,
    const at::Tensor& rowwise_data,
    const at::Tensor& rowwise_scale,
    const at::Tensor& columnwise_data,
    const at::Tensor& columnwise_scale,
    const at::Tensor& columnwise_amax,
    const at::Tensor& rht_output_t,
    const at::Tensor& active_rows_heavy_light,
    const at::Tensor& active_row_count,
    const at::Tensor& active_sort_rows_in,
    const at::Tensor& active_sort_rows_out,
    const at::Tensor& active_sort_keys_in,
    const at::Tensor& active_sort_keys_out,
    const at::Tensor& active_sort_temp,
    const at::Tensor& hardcap_score_max,
    const at::Tensor& hardcap_histogram,
    double base_ratio,
    double min_ratio,
    double max_ratio,
    double reference_heaviness,
    int64_t max_per_row,
    int64_t stats_threads,
    int64_t fill_threads,
    int64_t columnwise_source,
    int64_t rht_random_sign_mask_t,
    bool overlap_columnwise,
    bool direct_nomask);

std::vector<at::Tensor> adaptive_rowcol_loghist_quant_fast_out_cuda(
    const at::Tensor& input,
    const at::Tensor& flat_indices,
    const at::Tensor& outlier_values,
    const at::Tensor& outlier_cols,
    const at::Tensor& row_counts,
    const at::Tensor& row_offsets,
    const at::Tensor& selection_masks,
    const at::Tensor& num_selected,
    const at::Tensor& overflow,
    const at::Tensor& stats_amax,
    const at::Tensor& rowwise_data,
    const at::Tensor& rowwise_scale,
    const at::Tensor& columnwise_data,
    const at::Tensor& columnwise_scale,
    const at::Tensor& columnwise_amax,
    const at::Tensor& rht_output_t,
    const at::Tensor& scan_temp,
    const at::Tensor& log_hist,
    const at::Tensor& log_params,
    double ratio,
    int64_t hist_bins,
    int64_t min_exp,
    int64_t seed,
    int64_t capacity,
    int64_t stats_threads,
    int64_t fill_threads,
    int64_t columnwise_source,
    int64_t rht_random_sign_mask_t,
    bool overlap_columnwise,
    bool auto_expand_capacity);

std::vector<at::Tensor> adaptive_rowcol_refill_csr_cuda(
    const at::Tensor& input,
    const at::Tensor& row_offsets,
    const at::Tensor& selection_masks,
    int64_t selected_nnz,
    int64_t fill_threads);

std::vector<at::Tensor> adaptive_rowcol_cap_split_packed_cuda(
    const at::Tensor& row_offsets,
    const at::Tensor& row_ks,
    const at::Tensor& row_values,
    int64_t rows,
    int64_t cols,
    int64_t cap);

std::vector<at::Tensor> adaptive_rowcol_policy_split_packed_cuda(
    const at::Tensor& row_offsets,
    const at::Tensor& row_ks,
    const at::Tensor& row_values,
    int64_t rows,
    int64_t cols,
    int64_t policy_mode,
    int64_t param0,
    int64_t param1);

std::vector<at::Tensor> adaptive_rowcol_policy_bucket_split_packed_cuda(
    const at::Tensor& row_offsets,
    const at::Tensor& row_ks,
    const at::Tensor& row_values,
    int64_t rows,
    int64_t cols,
    int64_t policy_mode,
    int64_t param0,
    int64_t param1);

std::vector<at::Tensor> adaptive_rowcol_direct_split_packed_cuda(
    const at::Tensor& input,
    const at::Tensor& row_offsets,
    const at::Tensor& selection_masks,
    int64_t selected_nnz,
    int64_t policy_mode,
    int64_t param0,
    int64_t param1,
    bool use_bucket,
    int64_t fill_threads);

std::vector<at::Tensor> adaptive_rowcol_quant_fast(
    const at::Tensor& input,
    double base_ratio,
    double min_ratio,
    double max_ratio,
    double reference_heaviness,
    int64_t capacity,
    bool emit_dense_main,
    int64_t stats_threads,
    int64_t fill_threads,
    int64_t columnwise_source,
    int64_t rht_random_sign_mask_t,
    bool overlap_columnwise,
    bool direct_nomask,
    bool build_active_schedule,
    bool build_unsorted_active_rows,
    double threshold_sigma_override) {
  TORCH_CHECK(input.is_cuda(), "input must be a CUDA tensor");
  TORCH_CHECK(input.is_contiguous(), "input must be contiguous");
  TORCH_CHECK(input.dim() == 2, "input must be a 2D [M, K] tensor");
  return adaptive_rowcol_quant_fast_cuda(input,
                                         base_ratio,
                                         min_ratio,
                                         max_ratio,
                                         reference_heaviness,
                                         capacity,
                                         emit_dense_main,
                                         stats_threads,
                                         fill_threads,
                                         columnwise_source,
                                         rht_random_sign_mask_t,
                                         overlap_columnwise,
                                         direct_nomask,
                                         build_active_schedule,
                                         build_unsorted_active_rows,
                                         threshold_sigma_override);
}

int64_t adaptive_rowcol_scan_temp_bytes(int64_t rows) {
  return adaptive_rowcol_scan_temp_bytes_cuda(rows);
}

int64_t adaptive_rowcol_active_sort_temp_bytes(int64_t rows) {
  return adaptive_rowcol_active_sort_temp_bytes_cuda(rows);
}

std::vector<at::Tensor> adaptive_rowcol_quant_fast_out(
    const at::Tensor& input,
    const at::Tensor& flat_indices,
    const at::Tensor& outlier_values,
    const at::Tensor& outlier_cols,
    const at::Tensor& row_counts,
    const at::Tensor& row_offsets,
    const at::Tensor& selection_masks,
    const at::Tensor& num_selected,
    const at::Tensor& overflow,
    const at::Tensor& stats_amax,
    const at::Tensor& rowwise_data,
    const at::Tensor& rowwise_scale,
    const at::Tensor& columnwise_data,
    const at::Tensor& columnwise_scale,
    const at::Tensor& columnwise_amax,
    const at::Tensor& rht_output_t,
    const at::Tensor& scan_temp,
    const at::Tensor& packed_records,
    const at::Tensor& active_rows_heavy_light,
    const at::Tensor& active_row_count,
    const at::Tensor& active_sort_rows_in,
    const at::Tensor& active_sort_rows_out,
    const at::Tensor& active_sort_keys_in,
    const at::Tensor& active_sort_keys_out,
    const at::Tensor& active_sort_temp,
    const at::Tensor& hardcap_score_max,
    const at::Tensor& hardcap_histogram,
    double base_ratio,
    double min_ratio,
    double max_ratio,
    double reference_heaviness,
    int64_t capacity,
    int64_t stats_threads,
    int64_t fill_threads,
    int64_t columnwise_source,
    int64_t rht_random_sign_mask_t,
    bool overlap_columnwise,
    bool auto_expand_capacity,
    bool emit_packed_records,
    bool build_active_schedule,
    bool emit_direct_split,
    int64_t direct_policy_mode,
    int64_t direct_param0,
    int64_t direct_param1,
    bool direct_use_bucket,
    bool direct_no_host_slice) {
  TORCH_CHECK(input.is_cuda(), "input must be a CUDA tensor");
  TORCH_CHECK(input.is_contiguous(), "input must be contiguous");
  TORCH_CHECK(input.dim() == 2, "input must be a 2D [M, K] tensor");
  return adaptive_rowcol_quant_fast_out_cuda(input,
                                             flat_indices,
                                             outlier_values,
                                             outlier_cols,
                                             row_counts,
                                             row_offsets,
                                             selection_masks,
                                             num_selected,
                                             overflow,
                                             stats_amax,
                                             rowwise_data,
                                             rowwise_scale,
                                             columnwise_data,
                                             columnwise_scale,
                                             columnwise_amax,
                                             rht_output_t,
                                             scan_temp,
                                             packed_records,
                                             active_rows_heavy_light,
                                             active_row_count,
                                             active_sort_rows_in,
                                             active_sort_rows_out,
                                             active_sort_keys_in,
                                             active_sort_keys_out,
                                             active_sort_temp,
                                             hardcap_score_max,
                                             hardcap_histogram,
                                             base_ratio,
                                             min_ratio,
                                             max_ratio,
                                             reference_heaviness,
                                             capacity,
                                             stats_threads,
                                             fill_threads,
                                             columnwise_source,
                                             rht_random_sign_mask_t,
                                             overlap_columnwise,
                                             auto_expand_capacity,
                                             emit_packed_records,
                                             build_active_schedule,
                                             emit_direct_split,
                                             direct_policy_mode,
                                             direct_param0,
                                             direct_param1,
                                             direct_use_bucket,
                                             direct_no_host_slice);
}

std::vector<at::Tensor> adaptive_rowcol_quant_fast_padded_out(
    const at::Tensor& input,
    const at::Tensor& padded_values,
    const at::Tensor& padded_cols,
    const at::Tensor& row_counts,
    const at::Tensor& selection_masks,
    const at::Tensor& num_selected,
    const at::Tensor& overflow,
    const at::Tensor& overflow_rows,
    const at::Tensor& overflow_cols,
    const at::Tensor& overflow_values,
    const at::Tensor& overflow_count,
    const at::Tensor& stats_amax,
    const at::Tensor& rowwise_data,
    const at::Tensor& rowwise_scale,
    const at::Tensor& columnwise_data,
    const at::Tensor& columnwise_scale,
    const at::Tensor& columnwise_amax,
    const at::Tensor& rht_output_t,
    const at::Tensor& active_rows_heavy_light,
    const at::Tensor& active_row_count,
    const at::Tensor& active_sort_rows_in,
    const at::Tensor& active_sort_rows_out,
    const at::Tensor& active_sort_keys_in,
    const at::Tensor& active_sort_keys_out,
    const at::Tensor& active_sort_temp,
    const at::Tensor& hardcap_score_max,
    const at::Tensor& hardcap_histogram,
    double base_ratio,
    double min_ratio,
    double max_ratio,
    double reference_heaviness,
    int64_t max_per_row,
    int64_t stats_threads,
    int64_t fill_threads,
    int64_t columnwise_source,
    int64_t rht_random_sign_mask_t,
    bool overlap_columnwise,
    bool direct_nomask) {
  TORCH_CHECK(input.is_cuda(), "input must be a CUDA tensor");
  TORCH_CHECK(input.is_contiguous(), "input must be contiguous");
  TORCH_CHECK(input.dim() == 2, "input must be a 2D [M, K] tensor");
  return adaptive_rowcol_quant_fast_padded_out_cuda(input,
                                                    padded_values,
                                                    padded_cols,
                                                    row_counts,
                                                    selection_masks,
                                                    num_selected,
                                                    overflow,
                                                    overflow_rows,
                                                    overflow_cols,
                                                    overflow_values,
                                                    overflow_count,
                                                    stats_amax,
                                                    rowwise_data,
                                                    rowwise_scale,
                                                    columnwise_data,
                                                    columnwise_scale,
                                                    columnwise_amax,
                                                    rht_output_t,
                                                    active_rows_heavy_light,
                                                    active_row_count,
                                                    active_sort_rows_in,
                                                    active_sort_rows_out,
                                                    active_sort_keys_in,
                                                    active_sort_keys_out,
                                                    active_sort_temp,
                                                    hardcap_score_max,
                                                    hardcap_histogram,
                                                    base_ratio,
                                                    min_ratio,
                                                    max_ratio,
                                                    reference_heaviness,
                                                    max_per_row,
                                                    stats_threads,
                                                    fill_threads,
                                                    columnwise_source,
                                                    rht_random_sign_mask_t,
                                                    overlap_columnwise,
                                                    direct_nomask);
}

std::vector<at::Tensor> adaptive_rowcol_loghist_quant_fast_out(
    const at::Tensor& input,
    const at::Tensor& flat_indices,
    const at::Tensor& outlier_values,
    const at::Tensor& outlier_cols,
    const at::Tensor& row_counts,
    const at::Tensor& row_offsets,
    const at::Tensor& selection_masks,
    const at::Tensor& num_selected,
    const at::Tensor& overflow,
    const at::Tensor& stats_amax,
    const at::Tensor& rowwise_data,
    const at::Tensor& rowwise_scale,
    const at::Tensor& columnwise_data,
    const at::Tensor& columnwise_scale,
    const at::Tensor& columnwise_amax,
    const at::Tensor& rht_output_t,
    const at::Tensor& scan_temp,
    const at::Tensor& log_hist,
    const at::Tensor& log_params,
    double ratio,
    int64_t hist_bins,
    int64_t min_exp,
    int64_t seed,
    int64_t capacity,
    int64_t stats_threads,
    int64_t fill_threads,
    int64_t columnwise_source,
    int64_t rht_random_sign_mask_t,
    bool overlap_columnwise,
    bool auto_expand_capacity) {
  TORCH_CHECK(input.is_cuda(), "input must be a CUDA tensor");
  TORCH_CHECK(input.is_contiguous(), "input must be contiguous");
  TORCH_CHECK(input.dim() == 2, "input must be a 2D [M, K] tensor");
  return adaptive_rowcol_loghist_quant_fast_out_cuda(input,
                                                     flat_indices,
                                                     outlier_values,
                                                     outlier_cols,
                                                     row_counts,
                                                     row_offsets,
                                                     selection_masks,
                                                     num_selected,
                                                     overflow,
                                                     stats_amax,
                                                     rowwise_data,
                                                     rowwise_scale,
                                                     columnwise_data,
                                                     columnwise_scale,
                                                     columnwise_amax,
                                                     rht_output_t,
                                                     scan_temp,
                                                     log_hist,
                                                     log_params,
                                                     ratio,
                                                     hist_bins,
                                                     min_exp,
                                                     seed,
                                                     capacity,
                                                     stats_threads,
                                                     fill_threads,
                                                     columnwise_source,
                                                     rht_random_sign_mask_t,
                                                     overlap_columnwise,
                                                     auto_expand_capacity);
}

std::vector<at::Tensor> adaptive_rowcol_refill_csr(
    const at::Tensor& input,
    const at::Tensor& row_offsets,
    const at::Tensor& selection_masks,
    int64_t selected_nnz,
    int64_t fill_threads) {
  TORCH_CHECK(input.is_cuda(), "input must be a CUDA tensor");
  TORCH_CHECK(input.is_contiguous(), "input must be contiguous");
  TORCH_CHECK(input.dim() == 2, "input must be a 2D [M, K] tensor");
  return adaptive_rowcol_refill_csr_cuda(
      input, row_offsets, selection_masks, selected_nnz, fill_threads);
}

std::vector<at::Tensor> adaptive_rowcol_cap_split_packed(
    const at::Tensor& row_offsets,
    const at::Tensor& row_ks,
    const at::Tensor& row_values,
    int64_t rows,
    int64_t cols,
    int64_t cap) {
  TORCH_CHECK(row_offsets.is_cuda(), "row_offsets must be CUDA");
  TORCH_CHECK(row_ks.is_cuda(), "row_ks must be CUDA");
  TORCH_CHECK(row_values.is_cuda(), "row_values must be CUDA");
  TORCH_CHECK(row_offsets.is_contiguous(), "row_offsets must be contiguous");
  TORCH_CHECK(row_ks.is_contiguous(), "row_ks must be contiguous");
  TORCH_CHECK(row_values.is_contiguous(), "row_values must be contiguous");
  return adaptive_rowcol_cap_split_packed_cuda(row_offsets, row_ks, row_values, rows, cols, cap);
}

std::vector<at::Tensor> adaptive_rowcol_policy_split_packed(
    const at::Tensor& row_offsets,
    const at::Tensor& row_ks,
    const at::Tensor& row_values,
    int64_t rows,
    int64_t cols,
    int64_t policy_mode,
    int64_t param0,
    int64_t param1) {
  TORCH_CHECK(row_offsets.is_cuda(), "row_offsets must be CUDA");
  TORCH_CHECK(row_ks.is_cuda(), "row_ks must be CUDA");
  TORCH_CHECK(row_values.is_cuda(), "row_values must be CUDA");
  TORCH_CHECK(row_offsets.is_contiguous(), "row_offsets must be contiguous");
  TORCH_CHECK(row_ks.is_contiguous(), "row_ks must be contiguous");
  TORCH_CHECK(row_values.is_contiguous(), "row_values must be contiguous");
  return adaptive_rowcol_policy_split_packed_cuda(
      row_offsets, row_ks, row_values, rows, cols, policy_mode, param0, param1);
}

std::vector<at::Tensor> adaptive_rowcol_policy_bucket_split_packed(
    const at::Tensor& row_offsets,
    const at::Tensor& row_ks,
    const at::Tensor& row_values,
    int64_t rows,
    int64_t cols,
    int64_t policy_mode,
    int64_t param0,
    int64_t param1) {
  TORCH_CHECK(row_offsets.is_cuda(), "row_offsets must be CUDA");
  TORCH_CHECK(row_ks.is_cuda(), "row_ks must be CUDA");
  TORCH_CHECK(row_values.is_cuda(), "row_values must be CUDA");
  TORCH_CHECK(row_offsets.is_contiguous(), "row_offsets must be contiguous");
  TORCH_CHECK(row_ks.is_contiguous(), "row_ks must be contiguous");
  TORCH_CHECK(row_values.is_contiguous(), "row_values must be contiguous");
  return adaptive_rowcol_policy_bucket_split_packed_cuda(
      row_offsets, row_ks, row_values, rows, cols, policy_mode, param0, param1);
}

std::vector<at::Tensor> adaptive_rowcol_direct_split_packed(
    const at::Tensor& input,
    const at::Tensor& row_offsets,
    const at::Tensor& selection_masks,
    int64_t selected_nnz,
    int64_t policy_mode,
    int64_t param0,
    int64_t param1,
    bool use_bucket,
    int64_t fill_threads) {
  TORCH_CHECK(input.is_cuda(), "input must be CUDA");
  TORCH_CHECK(row_offsets.is_cuda(), "row_offsets must be CUDA");
  TORCH_CHECK(selection_masks.is_cuda(), "selection_masks must be CUDA");
  TORCH_CHECK(input.is_contiguous(), "input must be contiguous");
  TORCH_CHECK(row_offsets.is_contiguous(), "row_offsets must be contiguous");
  TORCH_CHECK(selection_masks.is_contiguous(), "selection_masks must be contiguous");
  return adaptive_rowcol_direct_split_packed_cuda(input,
                                                  row_offsets,
                                                  selection_masks,
                                                  selected_nnz,
                                                  policy_mode,
                                                  param0,
                                                  param1,
                                                  use_bucket,
                                                  fill_threads);
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("adaptive_rowcol_scan_temp_bytes",
        &adaptive_rowcol_scan_temp_bytes,
        py::arg("rows"));
  m.def("adaptive_rowcol_active_sort_temp_bytes",
        &adaptive_rowcol_active_sort_temp_bytes,
        py::arg("rows"));
  m.def("adaptive_rowcol_quant_fast",
        &adaptive_rowcol_quant_fast,
        py::arg("input"),
        py::arg("base_ratio"),
        py::arg("min_ratio"),
        py::arg("max_ratio"),
        py::arg("reference_heaviness"),
        py::arg("capacity"),
        py::arg("emit_dense_main") = false,
        py::arg("stats_threads") = 256,
        py::arg("fill_threads") = 128,
        py::arg("columnwise_source") = 1,
        py::arg("rht_random_sign_mask_t") = 55272,
        py::arg("overlap_columnwise") = true,
        py::arg("direct_nomask") = false,
        py::arg("build_active_schedule") = false,
        py::arg("build_unsorted_active_rows") = false,
        py::arg("threshold_sigma_override") = -1.0);
  m.def("adaptive_rowcol_quant_fast_out",
        &adaptive_rowcol_quant_fast_out,
        py::arg("input"),
        py::arg("flat_indices"),
        py::arg("outlier_values"),
        py::arg("outlier_cols"),
        py::arg("row_counts"),
        py::arg("row_offsets"),
        py::arg("selection_masks"),
        py::arg("num_selected"),
        py::arg("overflow"),
        py::arg("stats_amax"),
        py::arg("rowwise_data"),
        py::arg("rowwise_scale"),
        py::arg("columnwise_data"),
        py::arg("columnwise_scale"),
        py::arg("columnwise_amax"),
        py::arg("rht_output_t"),
        py::arg("scan_temp"),
        py::arg("packed_records"),
        py::arg("active_rows_heavy_light"),
        py::arg("active_row_count"),
        py::arg("active_sort_rows_in"),
        py::arg("active_sort_rows_out"),
        py::arg("active_sort_keys_in"),
        py::arg("active_sort_keys_out"),
        py::arg("active_sort_temp"),
        py::arg("hardcap_score_max"),
        py::arg("hardcap_histogram"),
        py::arg("base_ratio"),
        py::arg("min_ratio"),
        py::arg("max_ratio"),
        py::arg("reference_heaviness"),
        py::arg("capacity"),
        py::arg("stats_threads") = 256,
        py::arg("fill_threads") = 128,
        py::arg("columnwise_source") = 1,
        py::arg("rht_random_sign_mask_t") = 55272,
        py::arg("overlap_columnwise") = true,
        py::arg("auto_expand_capacity") = false,
        py::arg("emit_packed_records") = false,
        py::arg("build_active_schedule") = true,
        py::arg("emit_direct_split") = false,
        py::arg("direct_policy_mode") = -1,
        py::arg("direct_param0") = 0,
        py::arg("direct_param1") = 0,
        py::arg("direct_use_bucket") = false,
        py::arg("direct_no_host_slice") = false);
  m.def("adaptive_rowcol_quant_fast_padded_out",
        &adaptive_rowcol_quant_fast_padded_out,
        py::arg("input"),
        py::arg("padded_values"),
        py::arg("padded_cols"),
        py::arg("row_counts"),
        py::arg("selection_masks"),
        py::arg("num_selected"),
        py::arg("overflow"),
        py::arg("overflow_rows"),
        py::arg("overflow_cols"),
        py::arg("overflow_values"),
        py::arg("overflow_count"),
        py::arg("stats_amax"),
        py::arg("rowwise_data"),
        py::arg("rowwise_scale"),
        py::arg("columnwise_data"),
        py::arg("columnwise_scale"),
        py::arg("columnwise_amax"),
        py::arg("rht_output_t"),
        py::arg("active_rows_heavy_light"),
        py::arg("active_row_count"),
        py::arg("active_sort_rows_in"),
        py::arg("active_sort_rows_out"),
        py::arg("active_sort_keys_in"),
        py::arg("active_sort_keys_out"),
        py::arg("active_sort_temp"),
        py::arg("hardcap_score_max"),
        py::arg("hardcap_histogram"),
        py::arg("base_ratio"),
        py::arg("min_ratio"),
        py::arg("max_ratio"),
        py::arg("reference_heaviness"),
        py::arg("max_per_row"),
        py::arg("stats_threads") = 256,
        py::arg("fill_threads") = 128,
        py::arg("columnwise_source") = 1,
        py::arg("rht_random_sign_mask_t") = 55272,
        py::arg("overlap_columnwise") = true,
        py::arg("direct_nomask") = false);
  m.def("adaptive_rowcol_loghist_quant_fast_out",
        &adaptive_rowcol_loghist_quant_fast_out,
        py::arg("input"),
        py::arg("flat_indices"),
        py::arg("outlier_values"),
        py::arg("outlier_cols"),
        py::arg("row_counts"),
        py::arg("row_offsets"),
        py::arg("selection_masks"),
        py::arg("num_selected"),
        py::arg("overflow"),
        py::arg("stats_amax"),
        py::arg("rowwise_data"),
        py::arg("rowwise_scale"),
        py::arg("columnwise_data"),
        py::arg("columnwise_scale"),
        py::arg("columnwise_amax"),
        py::arg("rht_output_t"),
        py::arg("scan_temp"),
        py::arg("log_hist"),
        py::arg("log_params"),
        py::arg("ratio"),
        py::arg("hist_bins"),
        py::arg("min_exp"),
        py::arg("seed"),
        py::arg("capacity"),
        py::arg("stats_threads") = 256,
        py::arg("fill_threads") = 128,
        py::arg("columnwise_source") = 1,
        py::arg("rht_random_sign_mask_t") = 55272,
        py::arg("overlap_columnwise") = true,
        py::arg("auto_expand_capacity") = false);
  m.def("adaptive_rowcol_refill_csr",
        &adaptive_rowcol_refill_csr,
        py::arg("input"),
        py::arg("row_offsets"),
        py::arg("selection_masks"),
        py::arg("selected_nnz"),
        py::arg("fill_threads") = 128);
  m.def("adaptive_rowcol_cap_split_packed",
        &adaptive_rowcol_cap_split_packed,
        py::arg("row_offsets"),
        py::arg("row_ks"),
        py::arg("row_values"),
        py::arg("rows"),
        py::arg("cols"),
        py::arg("cap"));
  m.def("adaptive_rowcol_policy_split_packed",
        &adaptive_rowcol_policy_split_packed,
        py::arg("row_offsets"),
        py::arg("row_ks"),
        py::arg("row_values"),
        py::arg("rows"),
        py::arg("cols"),
        py::arg("policy_mode"),
        py::arg("param0"),
        py::arg("param1"));
  m.def("adaptive_rowcol_policy_bucket_split_packed",
        &adaptive_rowcol_policy_bucket_split_packed,
        py::arg("row_offsets"),
        py::arg("row_ks"),
        py::arg("row_values"),
        py::arg("rows"),
        py::arg("cols"),
        py::arg("policy_mode"),
        py::arg("param0"),
        py::arg("param1"));
  m.def("adaptive_rowcol_direct_split_packed",
        &adaptive_rowcol_direct_split_packed,
        py::arg("input"),
        py::arg("row_offsets"),
        py::arg("selection_masks"),
        py::arg("selected_nnz"),
        py::arg("policy_mode"),
        py::arg("param0"),
        py::arg("param1"),
        py::arg("use_bucket") = false,
        py::arg("fill_threads") = 128);
}
